#import "./PoseStampedFragment.gql"

query poseStampedQuery {
  poseStampedMessage {
    ...PoseStampedMessage
  }
}

subscription poseStampedSubscription {
  poseStampedMessage {
    ...PoseStampedMessage
  }
}

mutation poseStampedMutate {
  poseStampedMessage {
    ...PoseStampedMessage
  }
}
