fragment ImuMessage on ImuMessage {
  seq
  secs
  nsecs
  frame_id
  orientation_x
  orientation_y
  orientation_z
  orientation_w
  angular_velocity_x
  angular_velocity_y
  angular_velocity_z
  linear_acceleration_x
  linear_acceleration_y
  linear_acceleration_z
}