fragment Imu on Imu {
  seq
  secs
  nsecs
  frameId
  orientationX
  orientationY
  orientationZ
  orientationW
  angularVelocityX
  angularVelocityY
  angularVelocityZ
  linearAccelerationX
  linearAccelerationY
  linearAccelerationZ
}