#import "./MaverickServiceListFragment.gql"

query maverickServiceListQuery {
  MaverickServiceList {
    ...MaverickServiceList
  }
}

subscription maverickServiceListSubscription {
  MaverickServiceList {
    ...MaverickServiceList
  }
}
