#import "./MaverickServiceFragment.gql"

query maverickServiceQuery($name: String!) {
  MaverickService(name: $name) {
    ...MaverickService
  }
}

subscription maverickServiceSubscription($name: String!) {
  MaverickService(name: $name) {
    ...MaverickService
  }
}

subscription maverickServicesSubscription {
  MaverickService {
    ...MaverickService
  }
}

mutation maverickServiceEnabledMutate($name: String!, $enabled: Boolean!) {
  MaverickService(name: $name, enabled: $enabled) {
    ...MaverickService
  }
}

mutation maverickServiceRunningMutate($name: String!, $running: Boolean!) {
  MaverickService(name: $name, running: $running) {
    ...MaverickService
  }
}
