#import "./MissionListFragment.gql"

query missionListQuery($id: String!) {
  MissionList(id: $id) {
    ...MissionList
  }
}

subscription missionListSubscription($id: String!) {
  MissionList(id: $id) {
    ...MissionList
  }
}

mutation missionListMutate($id: String!, $mission: [MissionInput]!) {
  MissionList(id: $id, mission: $mission) {
    ...MissionList
  }
}
