#import "./MissionFragment.gql"

query missionQuery {
  Mission {
    ...Mission
  }
}

subscription missionSubscription {
  Mission {
    ...Mission
  }
}

mutation missionMutate {
  Mission {
    ...Mission
  }
}
