fragment MissionList on MissionList {
  id
  total
  updateTime
  mission {
    seq
    isCurrent
    autocontinue
    frame
    command
    param1
    param2
    param3
    param4
    latitude
    longitude
    altitude
  }
}
