fragment MissionDatabase on MissionDatabase {
  id
  missions {
    id
    total
    mission {
      seq
      isCurrent
      autocontinue
      frame
      command
      param1
      param2
      param3
      param4
      latitude
      longitude
      altitude
    }
  }
}
