#import "./NavSatFixFragment.gql"

query navSatFixQuery {
  NavSatFixMessage {
    ...NavSatFixMessage
  }
}

subscription navSatFixSubscription {
  NavSatFixMessage {
    ...NavSatFixMessage
  }
}

mutation navSatFixMutate {
  NavSatFixMessage {
    ...NavSatFixMessage
  }
}
