#import "./NavSatFixFragment.gql"

query navSatFixQuery {
  NavSatFix {
    ...NavSatFix
  }
}

subscription navSatFixSubscription {
  NavSatFix {
    ...NavSatFix
  }
}

mutation navSatFixMutate {
  NavSatFix {
    ...NavSatFix
  }
}
