fragment Parameter on Parameter {
  id
  value
  meta {
    bitmask
    decimal
    documentation
    group
    humanGroup
    humanName
    increment
    max
    min
    rebootRequired
    unitText
    units
    values
  }
}