#import "./ParametersFragment.gql"

query paramQuery {
  ...Parameter
}

query paramsQuery {
  ParameterList(query: "*") {
    parameters {
      ...Parameter
    }
  }
}

subscription paramSubscription {
  Parameter {
    ...Parameter
  }
}

mutation updateParam ($id: String!, $value: ParamValue!) {
  Parameter(id: $id, value: $value) {
    ...Parameter
  }
}
