#import "./ParametersFragment.gql"

query paramsQuery {
  Params {
    ...Parameter
  }
}

subscription paramsSubscription {
  Params {
    ...Parameter
  }
}

mutation updateParam ($id: ID, $value: ParamValueType) {
  updateParam(id: $id, value: $value) {
    ok
    Param {
      id
      value
    }
  }
}
