fragment Parameter on Parameter {
  id
  value
  meta {
    bitmask
    decimal
    documentation
    group
    human_group
    human_name
    increment
    max
    min
    reboot_required
    type
    unit_text
    units
    values
  }
}