fragment PoseStampedMessage on PoseStampedMessage {
  seq
  secs
  nsecs
  frame_id
  pose_position_x
  pose_position_y
  pose_position_z
  pose_orientation_x
  pose_orientation_y
  pose_orientation_z
  pose_orientation_w
}