#import "./PoseStampedFragment.gql"

query poseStampedQuery {
  PoseStampedMessage {
    ...PoseStampedMessage
  }
}

subscription poseStampedSubscription {
  PoseStampedMessage {
    ...PoseStampedMessage
  }
}

mutation poseStampedMutate {
  PoseStampedMessage {
    ...PoseStampedMessage
  }
}
