#import "./PoseStampedFragment.gql"

query poseStampedQuery {
  PoseStamped {
    ...PoseStamped
  }
}

subscription poseStampedSubscription {
  PoseStamped {
    ...PoseStamped
  }
}

mutation poseStampedMutate {
  PoseStamped {
    ...PoseStamped
  }
}
