#import "./StatusTextFragment.gql"

query statusTextQuery {
  StatusText {
    ...StatusText
  }
}

subscription statusTextSubscription {
  StatusText {
    ...StatusText
  }
}

mutation statusTextMutate {
  StatusText {
    ...StatusText
  }
}
