#import "./StateFragment.gql"

query stateQuery {
  StateMessage {
    ...StateMessage
  }
}

subscription stateSubscription {
  StateMessage {
    ...StateMessage
  }
}

mutation stateMutate {
  StateMessage {
    ...StateMessage
  }
}
