#import "./VehicleStateFragment.gql"

query vehicleStateQuery {
  VehicleState {
    ...VehicleState
  }
}

subscription vehicleStateSubscription {
  VehicleState {
    ...VehicleState
  }
}

mutation vehicleStateMutate($mode: String!) {
  VehicleState(mode: $mode) {
    ...VehicleState
  }
}
