#import "./VfrHudFragment.gql"

query vfrHudQuery {
  VfrHudMessage {
    ...VfrHudMessage
  }
}

subscription vfrHudSubscription {
  VfrHudMessage {
    ...VfrHudMessage
  }
}

mutation vfrHudMutate {
  VfrHudMessage {
    ...VfrHudMessage
  }
}
