#import "./VfrHudFragment.gql"

query vfrHudQuery {
  VfrHud {
    ...VfrHud
  }
}

subscription vfrHudSubscription {
  VfrHud {
    ...VfrHud
  }
}

mutation vfrHudMutate {
  VfrHud {
    ...VfrHud
  }
}
