#import "./ImuFragment.gql"

query imuQuery {
  ImuMessage {
    ...ImuMessage
  }
}

subscription imuSubscription {
  ImuMessage {
    ...ImuMessage
  }
}

mutation imuMutate {
  ImuMessage {
    ...ImuMessage
  }
}
