#import "./NavSatFixFragment.gql"

query navSatFixQuery {
  navSatFixMessage {
    ...NavSatFixMessage
  }
}

subscription navSatFixSubscription {
  navSatFixMessage {
    ...NavSatFixMessage
  }
}

mutation navSatFixMutate {
  navSatFixMessage {
    ...NavSatFixMessage
  }
}
