#import "./ParametersFragment.gql"

query paramsQuery {
  params {
    ...Parameter
  }
}

subscription paramsSubscription {
  params {
    ...Parameter
  }
}

mutation updateParam ($id: ID, $value: Float) {
  updateParam(id: $id, value: $value) {
    ok
    param {
      id
      value
    }
  }
}
