#import "./VfrHudFragment.gql"

query vfrHudQuery {
  vfrHudMessage {
    ...VfrHudMessage
  }
}

subscription vfrHudSubscription {
  vfrHudMessage {
    ...VfrHudMessage
  }
}

mutation vfrHudMutate {
  vfrHudMessage {
    ...VfrHudMessage
  }
}
